#!/usr/bin/env python3
"""Generate prose-only Bold variants with the pinned upstream geometry recipes.

Requires fonttools only at generation time; never writes to the upstream tree.
Letters/composites use actual Geist Bold. P is the native geometric Phi icon;
digits preserve Geist Mono's slashed zero and use an emboldened outline because
the pinned source ships only Mono Regular.
"""
import io
import os
from pathlib import Path
import subprocess
import xml.etree.ElementTree as ET
from fontTools.ttLib import TTFont

root = Path(__file__).resolve().parent.parent
pin = (root / 'qni-webgpu.ref').read_text().strip()
source = os.environ.get('QNI_WEBGPU_SOURCE', str(root / '.qni-webgpu-source'))
def show(path):
    return subprocess.check_output(['git', '-C', source, 'show', f'{pin}:{path}'])
recipe = {'__name__': 'pinned_glyph_recipe', '__file__': 'scripts/extract-gate-svg.py'}
exec(compile(show('scripts/extract-gate-svg.py'), 'pinned-extract-gate-svg.py', 'exec'), recipe)
fonts = {}
def font(weight):
    name = 'GeistMono-Regular.ttf' if weight == 'MonoRegular' else 'Geist-Bold.ttf'
    if name not in fonts:
        fonts[name] = TTFont(io.BytesIO(show('apps/web/assets/' + name)))
    return fonts[name]
recipe['font_for_weight'] = font
recipe['DEFAULT_WEIGHT'] = 'Bold'
for token in recipe['WEIGHT_FOR_TOKEN']:
    recipe['WEIGHT_FOR_TOKEN'][token] = 'Bold'
recipe['WEIGHT_FOR_CHAR']['+'] = 'Bold'
ET.register_namespace('', 'http://www.w3.org/2000/svg')
for token, name in [('Y','y'),('Z','z'),('S','s'),('S†','sdagger'),('T','t'),('T†','tdagger'),('P','p'),('√X','sqrtx'),('RX','rx'),('RY','ry'),('RZ','rz'),('QFT','qft'),('QFT†','qftdagger'),('0','digit0'),('1','digit1')]:
    element = ET.fromstring(recipe['extract'](token))
    element.set('data-font-weight', '700')
    element.set('data-source-sha', pin)
    element.set('aria-hidden', 'true')
    element.set('focusable', 'false')
    if token == 'P':
        for path in element.iter('{http://www.w3.org/2000/svg}path'):
            path.set('stroke-width', '2.25')
    elif token in ('0','1'):
        element.set('data-outline-emboldened', 'true')
        for path in element.iter('{http://www.w3.org/2000/svg}path'):
            path.set('stroke', 'currentColor')
            path.set('stroke-width', '48')
            path.set('stroke-linejoin', 'round')
            path.set('paint-order', 'stroke')
    output = root / 'src/assets/gates/bold' / (name + '.svg')
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text('<!-- Generated by scripts/extract-inline-glyphs.py; do not edit manually. -->\n' + ET.tostring(element, encoding='unicode') + '\n')
