#!/usr/bin/env python3
"""Generate an inline H or Plus outline from pinned Geist Bold (requires fonttools).

Uses the em-based 48px / 0.62 scale and centering from upstream
scripts/extract-gate-svg.py. Never writes to the upstream checkout.
"""
import argparse
import io
import os
from pathlib import Path
import subprocess
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--glyph', choices=('h', 'plus'), default='h')
args = parser.parse_args()
root = Path(__file__).resolve().parent.parent
pin = (root / 'qni-webgpu.ref').read_text().strip()
source = os.environ.get('QNI_WEBGPU_SOURCE', str(root / '.qni-webgpu-source'))
font = TTFont(io.BytesIO(subprocess.check_output([
    'git', '-C', source, 'show', f'{pin}:apps/web/assets/Geist-Bold.ttf',
])))
glyph_name = font.getBestCmap()[ord('H' if args.glyph == 'h' else '+')]
glyph_set = font.getGlyphSet()
box = font['glyf'][glyph_name]
pen = SVGPathPen(glyph_set)
glyph_set[glyph_name].draw(pen)
scale = 48 * 0.62 / font['head'].unitsPerEm
x = (48 - (box.xMax - box.xMin) * scale) / 2 - box.xMin * scale
y = (48 - (box.yMax - box.yMin) * scale) / 2 + box.yMax * scale
svg = f'''<!-- Generated by scripts/extract-inline-h.py --glyph {args.glyph}; do not edit manually. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" aria-hidden="true" focusable="false" data-font-weight="700" data-source-sha="{pin}">
  <g transform="translate({x:.3f} {y:.3f}) scale({scale:.6f} {-scale:.6f})">
    <path d="{pen.getCommands()}" fill="currentColor"/>
  </g>
</svg>
'''
(root / f'src/assets/{args.glyph}-bold.svg').write_text(svg)
